services:
  - type: web
    name: reconmate-ai-agent
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt && python generate_data.py && python reconcile.py && python ai_agent.py
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: GOOGLE_API_KEY
        sync: false
